source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SampleLib_Example', :exclusive => true do
  pod 'SampleLib', :path => '../'
end

target 'SampleLib_Tests', :exclusive => true do
  pod 'SampleLib', :path => '../'

  
end
